services:
  resume:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py tailwind install &&
             python manage.py tailwind start & 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET=your-dev-secret
