services:
  resume:
    container_name: resume
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn resume.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - SECRET=your-prod-secret
    networks:
      - app-network

volumes:
  static_volume:

networks:
  app-network:
    external: true