# Dockerfile.web

FROM python:3.13-slim

# Environment
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy Django app
COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
