FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies (including tailwindcss)
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of your app
COPY . .

# Set the default command
CMD ["npx", "tailwindcss", "-i", "./core/static/input.css", "-o", "./core/static/output.css", "--watch", "--poll"]